language: rust
cache: cargo
sudo: false

rust:
  - nightly
  - beta
  - stable

script:
  - rustup component add rustfmt clippy
  - cargo build --all-targets --verbose
  - cargo test --all-targets --verbose
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check